spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate-practice
    username: postgres
    password: postgres
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true